services:
  security_processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.security_processor
      args:
        BUILD_BIN_DIR: ${BUILD_BIN_DIR}
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/security_processor:${IMAGE_TAG}-${IMAGE_ARCH}
    platform: linux/${IMAGE_ARCH}
    container_name: security_processor
    restart: unless-stopped
    networks:
      - dds_net

  attack_env:
    build:
      context: ..
      dockerfile: docker/Dockerfile.attack_env
      args:
        BUILD_BIN_DIR: ${BUILD_BIN_DIR}
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/attack_env:${IMAGE_TAG}-${IMAGE_ARCH}
    platform: linux/${IMAGE_ARCH}
    container_name: attack_env
    restart: unless-stopped
    networks:
      - dds_net
    ports:
      - "45000:45000"

  security_monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.security_monitor
      args:
        BUILD_BIN_DIR: ${BUILD_BIN_DIR}
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/security_monitor:${IMAGE_TAG}-${IMAGE_ARCH}
    platform: linux/${IMAGE_ARCH}
    container_name: security_monitor
    restart: unless-stopped
    ports:
      - "48080:48080"
    volumes:
      - monitor_db:/app/data
    depends_on:
      - attack_env
    networks:
      - dds_net

networks:
  dds_net:
    driver: bridge

volumes:
  monitor_db:
